add php56 support + jinja2 templating to php modules
continuousphp/runtime-containers pull request #30
Opened 2020-09-07 23:10 UTC by RSchumacher13

#Add PHP 56 support + jinja2 templating to php-modules definition
- Doesn't alter the original behavior of the program, however, `/runtime-containers/components/php_modules/deb/php_modules.j2` replaces `/runtime-containers/components/php_modules/deb/php_modules.dtc` as asked in #17 
- Adds PHP 56 runtime
- Adapts Bats test to be performed on < PHP 7 environments

2020-09-09 12:35 UTC, Farouk-Lamri approved these changes

2020-09-09 14:12 UTC, Pierozi requested changes
I think you will have issue regarding the deployment of runtime php_custom.
check the ci script https://github.com/continuousphp/runtime-containers/blob/master/bin/ci.sh#L65-L69

The name of the image build locally and the tag does not match due to the fact that the script was design only for one runtime... must adapt it but still pushed to the same ECR in case of php...

2020-09-10 09:49 UTC, RSchumacher13 commented
> I think you will have issue regarding the deployment of runtime php_custom.
> check the ci script https://github.com/continuousphp/runtime-containers/blob/master/bin/ci.sh#L65-L69
> 
> The name of the image build locally and the tag does not match due to the fact that the script was design only for one runtime... must adapt it but still pushed to the same ECR in case of php...

Should be ok now. Conversion to semantic versioning is now done when building the image, and the ci script is using the $runtime variable instead of hardcoded php. php for > 7 and php_custom for 5.6.40 (obtained from devilbox/php-fpm:5.6-base

2020-09-10 14:12 UTC, Farouk-Lamri submitted a review, later dismissed

2020-09-10 14:57 UTC, fdewinne submitted a review, later dismissed

2020-09-11 08:49 UTC, Pierozi submitted a review, later dismissed

2020-09-11 08:59 UTC, Farouk-Lamri approved these changes

2020-09-11 09:00 UTC, merged